---
general:
  buildTool: "mta"

service:
  buildToolVersion: "MBTJ21N22"
  stages:
    Build:
      credentialVariables:
        # Map your Secret Text credential here
        - name: "BITBUCKET_TOKEN"
          credentialId: "bitbucket-token"
      runFirst:
        command: |
          set -e
          echo "== Bootstrap corporate repo =="
          if [ -z "${BITBUCKET_TOKEN}" ]; then
            echo "ERROR: BITBUCKET_TOKEN not set"; exit 1
          fi
          git config --global http.https://devstack.vwgroup.com/.extraheader "Authorization: Bearer ${BITBUCKET_TOKEN}"
          rm -rf source
          git clone https://devstack.vwgroup.com/bitbucket/scm/vwskdevops/ibantest.git source

          # bring code to cloudcitransfer for build/deploy
          mkdir -p cloudcitransfer
          cp -a source/. cloudcitransfer/.

          echo "== Source code from Bitbucket copied into cloudcitransfer =="

stages:
  Build:
    mavenExecuteStaticCodeChecks: false
    npmExecuteLint: false
  Acceptance:
    cfApiEndpoint: "https://api.cf.eu10-004.hana.ondemand.com"
    cfOrg: "VW_SK_klientportal-tst"
    cfSpace: "DEV_Build_SPC"
    deployType: "standard"
    cloudFoundryDeploy: true
    npmExecuteEndToEndTests: false
  Malware Scan:
    malwareExecuteScan: false
  Release:
    tmsExport: false
    tmsUpload: false
    cloudFoundryDeploy: false
  Additional Unit Tests:
    npmExecuteScripts: false
  Compliance:
    sonarExecuteScan: false

steps:
  artifactPrepareVersion:
    versioningType: "cloud_noTag"
  mtaBuild:
    source: "cloudcitransfer"