# .pipeline/config.yml (jump repo)

general:
  # We'll generate this file from the Bitbucket repo during Init
  pipelineConfigFile: dynamicConfig.yml

stages:
  Init:
    # Run this before any other stage so the workspace contains the Bitbucket sources
    runFirstCommands: |
      set -e
      echo "== Init: preparing workspace from corporate Bitbucket =="

      if [ -z "${BITBUCKET_TOKEN}" ]; then
        echo "ERROR: BITBUCKET_TOKEN is not set (add the Secret Text credential and map it to BITBUCKET_TOKEN in the job)."
        exit 1
      fi

      # Make git send Authorization: Bearer <token> to your Bitbucket host
      git config --global http.https://devstack.vwgroup.com/.extraheader "Authorization: Bearer ${BITBUCKET_TOKEN}"

      echo "[1/3] Cloning corporate repo into ./source ..."
      rm -rf source
      git clone https://devstack.vwgroup.com/bitbucket/scm/vwskdevops/ibantest.git source

      echo "[2/3] Writing pipeline overlay dynamicConfig.yml from Bitbucket repo ..."
      if [ -f source/.ci/params.yml ]; then
        cp source/.ci/params.yml dynamicConfig.yml
        echo "dynamicConfig.yml written from source/.ci/params.yml"
      elif [ -f source/.pipeline/config.yml ]; then
        cp source/.pipeline/config.yml dynamicConfig.yml
        echo "dynamicConfig.yml written from source/.pipeline/config.yml"
      else
        echo "ERROR: no pipeline config found in source/.ci/params.yml or source/.pipeline/config.yml"
        exit 1
      fi

      echo "[3/3] Syncing Bitbucket sources into workspace root so build steps see mta.yaml ..."
      rsync -a --delete source/ ./
      rm -rf source

  Build:
    # Nothing special here; after Init rsync, mta.yaml is at workspace root
    mavenExecuteStaticCodeChecks: false
    npmExecuteLint: false

  Acceptance:
    # Leave stage toggles minimal in the jump repo; details live in dynamicConfig.yml
    cloudFoundryDeploy: true
    npmExecuteEndToEndTests: false

  Malware Scan:
    malwareExecuteScan: false

  Release:
    cloudFoundryDeploy: false
    tmsExport: false
    tmsUpload: false

  Additional Unit Tests:
    npmExecuteScripts: false

  Compliance:
    sonarExecuteScan: false
