general:
  pipelineConfigFile: dynamicConfig.yml

stages:
  Build:
    runFirst: |
      set -e
      echo "== Bootstrap: start =="

      if [ -z "${BITBUCKET_TOKEN}" ]; then
        echo "ERROR: BITBUCKET_TOKEN is not set (map Secret Text credential to BITBUCKET_TOKEN in job)."
        exit 1
      fi

      # Make git send Authorization: Bearer <token> to your Bitbucket host
      git config --global http.https://devstack.vwgroup.com/.extraheader "Authorization: Bearer ${BITBUCKET_TOKEN}"

      echo "[1/3] Cloning corporate repo into ./source ..."
      rm -rf source
      git clone https://devstack.vwgroup.com/bitbucket/scm/vwskdevops/ibantest.git source

      echo "[2/3] Writing pipeline overlay dynamicConfig.yml from Bitbucket repo ..."
      if [ -f source/.ci/params.yml ]; then
        cp source/.ci/params.yml dynamicConfig.yml
        echo "dynamicConfig.yml written from source/.ci/params.yml"
      elif [ -f source/.pipeline/config.yml ]; then
        cp source/.pipeline/config.yml dynamicConfig.yml
        echo "dynamicConfig.yml written from source/.pipeline/config.yml"
      else
        echo "ERROR: no pipeline config found in source/.ci/params.yml or source/.pipeline/config.yml"
        exit 1
      fi

      echo "[3/3] Syncing Bitbucket sources into workspace root so build steps see mta.yaml ..."
      shopt -s dotglob || true
      cp -a source/* ./
      rm -rf source

      echo "== Bootstrap: done =="

    # keep the rest of your toggles here if you want
    mavenExecuteStaticCodeChecks: false
    npmExecuteLint: false

  Acceptance:
    cloudFoundryDeploy: true
    npmExecuteEndToEndTests: false

  Malware Scan:
    malwareExecuteScan: false
  Release:
    cloudFoundryDeploy: false
    tmsExport: false
    tmsUpload: false
  Additional Unit Tests:
    npmExecuteScripts: false
  Compliance:
    sonarExecuteScan: false
